name: CI Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  deno-version: "1.20.4"
  docker-registry: ghcr.io

jobs:

  ######################################################################################################################
  ## Validate
  ######################################################################################################################

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: ${{ env.deno-version }}

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

  ######################################################################################################################
  ## Build & Publish Docker Image
  ######################################################################################################################

  build-and-push-images:
    runs-on: ubuntu-latest
    needs: [lint]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Log in to the Container registry
        uses: docker/login-action@42d299face0c5c43a0487c477f595ac9cf22f1a7
        with:
          registry: ${{ env.docker-registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Add SHORT_SHA env property with commit short sha since GitHub doesn't provide it
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Get branch name since GitHub doesn't provide it
        id: branch-name
        uses: tj-actions/branch-names@7f0a69aa8e80f46987e8979c73ac9923d6a3c004

      - name: Determine tag to use
        uses: haya14busa/action-cond@fcf25c40aad2d8f13112d74eb825a2d48a9726bc
        id: tag-condition
        with:
          # Are we running on main (the default branch) or a PR that will merge into main?
          cond: ${{ steps.branch-name.outputs.is_default == 'true' }}
          # On main, we tag with a release name like "build14-abcd678" as well as "latest"
          if_true: ghcr.io/neolace-dev/improxy-gateway:build${{ github.run_number }}-${{ env.SHORT_SHA }},ghcr.io/neolace-dev/improxy-gateway:latest
          # For merge requests, just use the branch name as the image tag; we don't want to pollute the container
          # registry with too many random branch builds.
          if_false: ghcr.io/neolace-dev/improxy-gateway:${{ steps.branch-name.outputs.current_branch }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.10.0
        with:
          file: Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.tag-condition.outputs.value }}
          labels: |
            org.opencontainers.image.title=imgproxy-gateway
            org.opencontainers.image.description="A proxy for imgproxy"
            org.opencontainers.image.url=https://www.neolace.com
            org.opencontainers.image.source=https://github.com/neolace-dev/imgproxy-gateway
            org.opencontainers.image.revision=${{ github.sha }}
